QUAL: 8
MINL: 1300
MAXL: 1700
ID: 0.7
NUM_PROCESSES: 1
R_CLEANING: 1
MINAB: 1
SUBSAMPLING: 50000
NUM_PROCESSES: 1
TREE: 1
INPUT_DIR: "Minimal/fastq"
METADATA: "Minimal/metadata.csv"
DATABASE: "resources/SILVA_138_SSURef_tax_silva.fasta.gz"
