QUAL: 8
MINL: 1300
MAXL: 1700
ID: 0.7
NUM_PROCESSES: 1
R_CLEANING: 1
MINAB: 5
SUBSAMPLING: 50000
NUM_PROCESSES: 2
TREE: 0
INPUT_DIR: "SMALL/"
METADATA: "SMALL/"
DATABASE: "SMALL/SMALL_WITH_CHLOROFLEXI_reference.fasta"
