QUAL: 8
MINL: 1300
MAXL: 1700
ID: 0.7
NUM_PROCESSES: 1
R_CLEANING: 1
MINAB: 5
SUBSAMPLING: 50000
NUM_PROCESSES: 2
TREE: 0
OUT: "dryrun_out/"
INPUT_DIR: "SMALL/"
METADATA: "SMALL/"
DATABASE: "resources/SILVA_138.2_SSURef_tax_silva.fasta.gz"
NANOASV_PATH: $NANOASV_PATH