QUAL: 8
MINL: 1300
MAXL: 1700
ID: 0.3
NUM_PROCESSES: 1
R_CLEANING: 1
MINAB: 1
SUBSAMPLING: 50000
NUM_PROCESSES: 2
TREE: 0
INPUT_DIR: "SMALL/"
METADATA: "SMALL/"
DATABASE: "SMALL/NO_Chloroflexi_SMALL_reference.fasta"
